# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger: 
  - stg

pool:
  name: 'ERP_DEV'

jobs:
  - job: DotnetBuild
    steps:   
    - script: |
        export PATH=$PATH:/opt/dotnet3/
        cd aspnet-core/src/ProjectManagement.Migrator
        dotnet3 build
        dotnet3 publish
        cd bin/Debug/netcoreapp3.1/publish/
        zip -r backend_migrator.zip *
      displayName: 'Dotnet Build Migrator'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'aspnet-core/src/ProjectManagement.Migrator/bin/Debug/netcoreapp3.1/publish/backend_migrator.zip'
        ArtifactName: 'stg-dotnet-migrator-project'
        publishLocation: 'Container'
      displayName: 'Publish Artifacts Migrator'

    - script: |
        export PATH=$PATH:/opt/dotnet3/
        cd aspnet-core
        dotnet3 build
        dotnet3 publish
        cd src/ProjectManagement.Web.Host/bin/Debug/netcoreapp3.1/publish/
        zip -r backend_publish.zip *
      displayName: 'Dotnet Build Host'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'aspnet-core/src/ProjectManagement.Web.Host/bin/Debug/netcoreapp3.1/publish/backend_publish.zip'
        ArtifactName: 'stg-dotnet-host-project'
        publishLocation: 'Container'
      displayName: 'Publish Artifacts Host'

  - job: AngularBuild
    steps:
      - script: |
          cd angular/
          export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm use 14.17
          node -v
          rm -rf node_modules/
          npm cache clean --force
          echo "=== INSTALL PACKAGE ==="
          npm install
        displayName: 'Install Package'
      
      - script: |
          cd angular/
          export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm use 14.17 
          ng build --prod
        displayName: 'Build Frontend'
      
      - script: |
          cd angular/dist
          zip -r frontend_publish.zip *
        displayName: 'Compress Build FE'
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'angular/dist/frontend_publish.zip'
          ArtifactName: 'stg-fe-project'
          publishLocation: 'Container'
        displayName: 'Publish Artifacts Frontend'
            
          

