using OfficeOpenXml.FormulaParsing.Excel.Functions.Database;
using ProjectManagement.Helper;
using System;
using System.Collections.Generic;
using System.Text;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using System.Threading.Channels;

namespace ProjectManagement.Utils
{
    public class AuditLogUtils
    {
        public static Dictionary<string, string> Dict = new Dictionary<string, string>()
        {
            {"Abp.AspNetCore.Mvc.Controllers.AbpUserConfigurationController GetAll", "Trang Admin > Configurations"},
            {"ProjectManagement.APIs.AuditLogs.AuditLogAppService GetAllEmailAddressInAuditLog", "Trang Admin > AuditLogs"},
            {"ProjectManagement.APIs.AuditLogs.AuditLogAppService GetAllPagging", "Trang Admin > AuditLogs"},
            {"ProjectManagement.APIs.AuditSessions.AuditSessionAppService GetAllPaging", "AuditSessionAppService"},
            {"ProjectManagement.APIs.Branchs.BranchAppService Create", "Trang Admin > Branches"},
            {"ProjectManagement.APIs.Branchs.BranchAppService Delete", "Trang Admin > Branches"},
            {"ProjectManagement.APIs.Branchs.BranchAppService GetAllNotPagging", "Trang Admin > Branches"},
            {"ProjectManagement.APIs.Branchs.BranchAppService GetAllPaging", "Trang Admin > Branches"},
            {"ProjectManagement.APIs.Branchs.BranchAppService Update", "Trang Admin > Branches"},
            {"ProjectManagement.APIs.CheckPointUserDetails.CheckPointUserDetailAppService GetAll", "CheckPointUserAppService"},
            {"ProjectManagement.APIs.CheckPointUsers.CheckPointUserAppService Create", "CheckPointUserAppService"},
            {"ProjectManagement.APIs.CheckPointUsers.CheckPointUserAppService GetAllReviewBySelf", "CheckPointUserAppService"},
            {"ProjectManagement.APIs.CheckPointUsers.CheckPointUserAppService GetAllReviewForSelf", "CheckPointUserAppService"},
            {"ProjectManagement.APIs.CheckPointUsers.CheckPointUserAppService GetUserUnreview", "CheckPointUserAppService"},
            {"ProjectManagement.APIs.Clients.ClientAppService Create", "Trang Admin > Clients"},
            {"ProjectManagement.APIs.Clients.ClientAppService Delete", "Trang Admin > Clients"},
            {"ProjectManagement.APIs.Clients.ClientAppService GetAll", "Trang Admin > Clients"},
            {"ProjectManagement.APIs.Clients.ClientAppService GetAllClient", "Trang Admin > Clients"},
            {"ProjectManagement.APIs.Clients.ClientAppService GetAllInvoiceDate", "Trang Admin > Clients"},
            {"ProjectManagement.APIs.Clients.ClientAppService GetAllPaging", "Trang Admin > Clients"},
            {"ProjectManagement.APIs.Clients.ClientAppService GetAllPaymentDueBy", "Trang Admin > Clients"},
            {"ProjectManagement.APIs.Clients.ClientAppService getIdClientByCodeNcc", "Trang Admin > Clients"},
            {"ProjectManagement.APIs.Clients.ClientAppService Update", "Trang Admin > Clients"},
            {"ProjectManagement.APIs.CriteriaCategories.CriteriaCategoryAppService GetAllNoPagging", "CriteriaCategoryAppService"},
            {"ProjectManagement.APIs.Criterias.CriteriaAppService GetAllPaging", "CriteriaAppService"},
            {"ProjectManagement.APIs.Currencies.CurrencyAppService Create", "Trang Admin > Currencies"},
            {"ProjectManagement.APIs.Currencies.CurrencyAppService Delete", "Trang Admin > Currencies"},
            {"ProjectManagement.APIs.Currencies.CurrencyAppService GetAll", "Trang Admin > Currencies"},
            {"ProjectManagement.APIs.Currencies.CurrencyAppService GetAllPaging", "Trang Admin > Currencies"},
            {"ProjectManagement.APIs.Currencies.CurrencyAppService Update", "Trang Admin > Currencies"},
            {"ProjectManagement.APIs.HRM.HRMAppService ComfirmUserBackToWorkAfterQuitJob", "HRMAppService"},
            {"ProjectManagement.APIs.HRM.HRMAppService ConfirmMaternityUserComeBack", "HRMAppService"},
            {"ProjectManagement.APIs.HRM.HRMAppService ConfirmUserMaternityLeave", "HRMAppService"},
            {"ProjectManagement.APIs.HRM.HRMAppService ConfirmUserQuitJob", "HRMAppService"},
            {"ProjectManagement.APIs.HRM.HRMAppService CreateUserByHRM", "HRMAppService"},
            {"ProjectManagement.APIs.HRM.HRMAppService PlanUserMaternityLeave", "HRMAppService"},
            {"ProjectManagement.APIs.HRM.HRMAppService PlanUserQuitJob", "HRMAppService"},
            {"ProjectManagement.APIs.HRM.HRMAppService UpdateUserFromHRM", "HRMAppService"},
            {"ProjectManagement.APIs.HRM.HRMAppService UploadAvatarProjectUser", "HRMAppService"},
            {"ProjectManagement.APIs.HRMv2.Hrmv2AppService ConfirmUserBackToWork", "HRM2AppService"},
            {"ProjectManagement.APIs.HRMv2.Hrmv2AppService ConfirmUserMaternityLeave", "HRM2AppService"},
            {"ProjectManagement.APIs.HRMv2.Hrmv2AppService ConfirmUserPause", "HRM2AppService"},
            {"ProjectManagement.APIs.HRMv2.Hrmv2AppService ConfirmUserQuit", "HRM2AppService"},
            {"ProjectManagement.APIs.HRMv2.Hrmv2AppService ConfirmUserQuitJob", "HRM2AppService"},
            {"ProjectManagement.APIs.HRMv2.Hrmv2AppService ConfirmUserStatusToPause", "HRM2AppService"},
            {"ProjectManagement.APIs.HRMv2.Hrmv2AppService CreateUserByHRM", "HRM2AppService"},
            {"ProjectManagement.APIs.HRMv2.Hrmv2AppService PlanUserMaternityLeave", "HRM2AppService"},
            {"ProjectManagement.APIs.HRMv2.Hrmv2AppService PlanUserPause", "HRM2AppService"},
            {"ProjectManagement.APIs.HRMv2.Hrmv2AppService PlanUserQuit", "HRM2AppService"},
            {"ProjectManagement.APIs.HRMv2.Hrmv2AppService PlanUserQuitJob", "HRM2AppService"},
            {"ProjectManagement.APIs.HRMv2.Hrmv2AppService PlanUserStatusPause", "HRM2AppService"},
            {"ProjectManagement.APIs.HRMv2.Hrmv2AppService UpdateAvatarFromHrm", "HRM2AppService"},
            {"ProjectManagement.APIs.HRMv2.Hrmv2AppService UpdateUserFromHRM", "HRM2AppService"},
            {"ProjectManagement.APIs.Phases.PhaseAppService GetAllPhase", "PhaseAppService"},
            {"ProjectManagement.APIs.PMReportProjectIssues.PMReportProjectIssueAppService Create", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjectIssues.PMReportProjectIssueAppService Delete", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjectIssues.PMReportProjectIssueAppService EditMeetingNote", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjectIssues.PMReportProjectIssueAppService ProblemsOfTheWeek", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjectIssues.PMReportProjectIssueAppService Update", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjects.PMReportProjectAppService ConfirmJoinProject", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjects.PMReportProjectAppService GetAllByPmReport", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjects.PMReportProjectAppService GetAllByProject", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjects.PMReportProjectAppService GetchangedResourceByPmReport", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjects.PMReportProjectAppService GetInfoProject", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjects.PMReportProjectAppService GetPlannedResourceByPmReport", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjects.PMReportProjectAppService GetWorkingResourceOfProject", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjects.PMReportProjectAppService ProblemsOfTheWeekForReport", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjects.PMReportProjectAppService ReverseSeen", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjects.PMReportProjectAppService SendReport", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjects.PMReportProjectAppService SetDoneIssue", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjects.PMReportProjectAppService UpdateAutomationNote", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjects.PMReportProjectAppService UpdateHealth", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReportProjects.PMReportProjectAppService UpdateNote", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReports.PMReportAppService CloseReport", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReports.PMReportAppService CollectTimesheet", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReports.PMReportAppService Create", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReports.PMReportAppService Get", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReports.PMReportAppService GetAll", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReports.PMReportAppService GetAllPaging", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReports.PMReportAppService StatisticsReport", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.PMReports.PMReportAppService UpdateNote", "Trang Weekly Reports"},
            {"ProjectManagement.APIs.Positions.PositionAppService Create", "Trang Admin > Positions"},
            {"ProjectManagement.APIs.Positions.PositionAppService Delete", "Trang Admin > Positions"},
            {"ProjectManagement.APIs.Positions.PositionAppService GetAllNotPagging", "Trang Admin > Positions"},
            {"ProjectManagement.APIs.Positions.PositionAppService GetAllPaging", "Trang Admin > Positions"},
            {"ProjectManagement.APIs.Positions.PositionAppService GetAllPositionFilter", "Trang Admin > Positions"},
            {"ProjectManagement.APIs.Positions.PositionAppService Update", "Trang Admin > Positions"},
            {"ProjectManagement.APIs.ProjectCheckLists.ProjectCheckListAppService GetCheckListItemByProject", "Trang Projects"},
            {"ProjectManagement.APIs.ProjectCriteriaResults.ProjectCriteriaResultAppService GetAll", "Trang Projects"},
            {"ProjectManagement.APIs.ProjectCriterias.ProjectCriteriaAppService GetAll", "Trang Projects"},
            {"ProjectManagement.APIs.ProjectFiles.ProjectFileAppService DeleteFile", "Trang Projects"},
            {"ProjectManagement.APIs.ProjectFiles.ProjectFileAppService GetFiles", "Trang Projects"},
            {"ProjectManagement.APIs.ProjectFiles.ProjectFileAppService UploadFiles", "Trang Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService CloseProject", "Trang Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService Create", "Trang Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService CreateTrainingProject", "Trang Projects > Training Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService Delete", "Trang Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService Get", "Trang Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService GetAll", "Trang Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService GetAllPaging", "Trang Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService GetAllProductProjectPaging", "Trang Projects > Product Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService GetAllProjectInfo", "Trang Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService GetAllTrainingProjectPaging", "Trang Projects > Training Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService GetAllWorkingUserFromProject", "Trang Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService GetDetailTrainingProject", "Trang Projects > Training Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService GetMyProjects", "Trang Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService GetMyTrainingProjects", "Trang Projects > Training Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService GetOutsourcingPMs", "Trang Projects > Outsourcing Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService GetProductPMs", "Trang Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService GetProjectDetail", "Trang Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService GetTrainingPMs", "Trang Projects > Training Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService Update", "Trang Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService UpdateProjectDetail", "Trang Projects"},
            {"ProjectManagement.APIs.Projects.ProjectAppService UpdateTrainingProject", "Trang Projects > Training Projects"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService CheckInvoiceSetting", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService Create", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService Delete", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService GetAllByProject", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService GetAllProjectCanUsing", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService GetAvailableProjectsForSettingInvoice", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService GetBillInfo", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService GetDiscount", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService GetLastInvoiceNumber", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService GetParentInvoiceByProject", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService GetRate", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService Update", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService UpdateDiscount", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService UpdateInvoiceSetting", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService UpdateLastInvoiceNumber", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUserBills.ProjectUserBillAppService UpdateNote", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService AddUserToOutSourcingProject", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService AddUserToProductProject", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService AddUserToProject", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService AddUserToTrainingProject", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService CancelResourcePlan", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService ConfirmJoinProject", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService ConfirmJoinProjectOutsourcing", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService ConfirmJoinProjectProduct", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService ConfirmJoinProjectTraining", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService ConfirmOutProject", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService Create", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService EditProjectUserPlan", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService Get", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService GetAllPlannedUserByProject", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService GetAllWorkingProjectByUserId", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService GetAllWorkingUserByProject", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService GetProjectHistoryByUser", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService PlanNewResourceToProject", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService ReleaseUser", "Trang Admin > Users"},
            {"ProjectManagement.APIs.ProjectUsers.ProjectUserAppService UpdateCurrentResourceDetail", "Trang Admin > Users"},
            {"ProjectManagement.APIs.Public.PublicAppService CheckConnect", "PublicAppService"},
            {"ProjectManagement.APIs.Public.PublicAppService GetAllUser", "PublicAppService"},
            {"ProjectManagement.APIs.Public.PublicAppService GetConfigUri", "PublicAppService"},
            {"ProjectManagement.APIs.Public.PublicAppService GetUserLevelByLevelCode", "PublicAppService"},
            {"ProjectManagement.APIs.Resource.ResourceAppService AddUserFromPoolToTempProject", "Trang Resources"},
            {"ProjectManagement.APIs.Resource.ResourceAppService CancelAllResourcePlan", "Trang Resources"},
            {"ProjectManagement.APIs.Resource.ResourceAppService CancelPoolResourcePlan", "Trang Resources"},
            {"ProjectManagement.APIs.Resource.ResourceAppService CancelResourcePlan", "Trang Resources"},
            {"ProjectManagement.APIs.Resource.ResourceAppService ConfirmJoinProjectFromTabAllResource", "Trang Resources"},
            {"ProjectManagement.APIs.Resource.ResourceAppService ConfirmJoinProjectFromTabPool", "Trang Resources"},
            {"ProjectManagement.APIs.Resource.ResourceAppService ConfirmJoinProjectFromTabVendor", "Trang Resources"},
            {"ProjectManagement.APIs.Resource.ResourceAppService ConfirmOutProject", "Trang Resources"},
            {"ProjectManagement.APIs.Resource.ResourceAppService EditProjectUserPlan", "Trang Resources"},
            {"ProjectManagement.APIs.Resource.ResourceAppService GetAllPoolResource", "Trang Resources"},
            {"ProjectManagement.APIs.Resource.ResourceAppService GetAllResource", "Trang Resources"},
            {"ProjectManagement.APIs.Resource.ResourceAppService GetRetroReviewInternHistories", "Trang Resources"},
            {"ProjectManagement.APIs.Resource.ResourceAppService GetVendorResource", "Trang Resources"},
            {"ProjectManagement.APIs.Resource.ResourceAppService PlanEmployeeJoinOrOutProject", "Trang Resources"},
            {"ProjectManagement.APIs.Resource.ResourceAppService updateUserPoolNote", "Trang Resources"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService Cancel", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService CancelRequest", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService Create", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService CreateResourceRequestPlan", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService CreateTraining", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService Delete", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService DeleteMyRequest", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService DeleteResourceRequestPlan", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService GetAllByProject", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService GetAllPaging", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService GetById", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService GetPriorities", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService GetProjectUserRoles", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService GetRequestLevels", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService GetResourceRequestPlan", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService GetStatuses", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService GetTrainingRequestLevels", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService SetDone", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService Update", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService UpdateHPMNote", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService UpdatePMNote", "Trang Resource Requests"},
            {"ProjectManagement.APIs.ResourceRequests.ResourceRequestAppService UpdateResourceRequestPlan", "Trang Resource Requests"},
            {"ProjectManagement.APIs.Skills.SkillAppService Create", "Trang Admin > Skills"},
            {"ProjectManagement.APIs.Skills.SkillAppService Delete", "Trang Admin > Skills"},
            {"ProjectManagement.APIs.Skills.SkillAppService GetAll", "Trang Admin > Skills"},
            {"ProjectManagement.APIs.Skills.SkillAppService GetAllPaging", "Trang Admin > Skills"},
            {"ProjectManagement.APIs.Skills.SkillAppService Update", "Trang Admin > Skills"},
            {"ProjectManagement.APIs.Talent.TalentAppService GetBranches", "TalentAppService"},
            {"ProjectManagement.APIs.Talent.TalentAppService GetPositions", "TalentAppService"},
            {"ProjectManagement.APIs.Talent.TalentAppService SendRecruitmentToTalent", "TalentAppService"},
            {"ProjectManagement.APIs.Technologys.TechnologyAppService Create", "Trang Admin > Project Technologies"},
            {"ProjectManagement.APIs.Technologys.TechnologyAppService Delete", "Trang Admin > Project Technologies"},
            {"ProjectManagement.APIs.Technologys.TechnologyAppService GetAll", "Trang Admin > Project Technologies"},
            {"ProjectManagement.APIs.Technologys.TechnologyAppService GetAllPaging", "Trang Admin > Project Technologies"},
            {"ProjectManagement.APIs.Technologys.TechnologyAppService Update", "Trang Admin > Project Technologies"},
            {"ProjectManagement.APIs.TimeSheetProjectBills.TimeSheetProjectBillAppService Create", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimeSheetProjectBills.TimeSheetProjectBillAppService GetAll", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimeSheetProjectBills.TimeSheetProjectBillAppService GetUserForTimesheetProjectBill", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimeSheetProjectBills.TimeSheetProjectBillAppService RemoveAccountTS", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimeSheetProjectBills.TimeSheetProjectBillAppService Update", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimeSheetProjectBills.TimeSheetProjectBillAppService UpdateTSOfPM", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService CheckTimesheetProjectSetting", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService Create", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService Delete", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService DownloadFileTimesheetProject", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService ExportInvoice", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService ExportInvoiceAsPDF", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService ExportInvoiceForTax", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService GetAllByProject", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService GetAllPM", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService GetAllProjectTimesheetByTimesheet", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService GetBillInfoChart", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService GetTotalAmountProjectTimesheetByTimesheet", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService SendInvoiceToFinfast", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService SetComplete", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService test", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService Update", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService UpdateFileTimeSheetProject", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService UpdateNote", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimesheetProjects.TimesheetProjectAppService UpdateTimesheetProject", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimeSheets.TimeSheetAppService Create", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimeSheets.TimeSheetAppService Delete", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimeSheets.TimeSheetAppService ForceDelete", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimeSheets.TimeSheetAppService GetAllPaging", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimeSheets.TimeSheetAppService GetListPMByProjectCode", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimeSheets.TimeSheetAppService ReverseActive", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimeSheets.TimeSheetAppService Update", "Trang Timesheets"},
            {"ProjectManagement.APIs.TimeSheets.TimeSheetAppService UpdateAvatarFromTimesheet", "Trang Timesheets"},
            {"ProjectManagement.APIs.TrainingRequests.TrainingRequestAppService CancelRequest", "Trang Training Requests"},
            {"ProjectManagement.APIs.TrainingRequests.TrainingRequestAppService Create", "Trang Training Requests"},
            {"ProjectManagement.APIs.TrainingRequests.TrainingRequestAppService Delete", "Trang Training Requests"},
            {"ProjectManagement.APIs.TrainingRequests.TrainingRequestAppService GetAllPaging", "Trang Training Requests"},
            {"ProjectManagement.APIs.TrainingRequests.TrainingRequestAppService GetById", "Trang Training Requests"},
            {"ProjectManagement.APIs.TrainingRequests.TrainingRequestAppService GetPriorities", "Trang Training Requests"},
            {"ProjectManagement.APIs.TrainingRequests.TrainingRequestAppService GetProjectUserRoles", "Trang Training Requests"},
            {"ProjectManagement.APIs.TrainingRequests.TrainingRequestAppService GetResourceRequestPlan", "Trang Training Requests"},
            {"ProjectManagement.APIs.TrainingRequests.TrainingRequestAppService GetStatuses", "Trang Training Requests"},
            {"ProjectManagement.APIs.TrainingRequests.TrainingRequestAppService GetTrainingRequestLevels", "Trang Training Requests"},
            {"ProjectManagement.APIs.TrainingRequests.TrainingRequestAppService Update", "Trang Training Requests"},
            {"ProjectManagement.APIs.TrainingRequests.TrainingRequestAppService UpdateHPMNote", "Trang Training Requests"},
            {"ProjectManagement.APIs.TrainingRequests.TrainingRequestAppService UpdatePMNote", "Trang Training Requests"},
            {"ProjectManagement.APIs.TS.TSAppService UpdateAllAvatarFromTimesheet", "TimeSheetAppService"},
            {"ProjectManagement.Authorization.Accounts.AccountAppService IsTenantAvailable", "Trang Login"},
            {"ProjectManagement.Configuration.ConfigurationAppService Change", "Trang Admin > Configurations"},
            {"ProjectManagement.Configuration.ConfigurationAppService ChangeProjectSetting", "Trang Admin > Configurations"},
            {"ProjectManagement.Configuration.ConfigurationAppService CheckConnectToFinfast", "Trang Admin > Configurations"},
            {"ProjectManagement.Configuration.ConfigurationAppService CheckConnectToHRM", "Trang Admin > Configurations"},
            {"ProjectManagement.Configuration.ConfigurationAppService CheckConnectToTalent", "Trang Admin > Configurations"},
            {"ProjectManagement.Configuration.ConfigurationAppService CheckConnectToTimesheet", "Trang Admin > Configurations"},
            {"ProjectManagement.Configuration.ConfigurationAppService Get", "Trang Admin > Configurations"},
            {"ProjectManagement.Configuration.ConfigurationAppService GetTimeCountDown", "Trang Admin > Configurations"},
            {"ProjectManagement.Configuration.ConfigurationAppService SetTimeCountDown", "Trang Admin > Configurations"},
            {"ProjectManagement.Controllers.TokenAuthController Authenticate", "Trang Login"},
            {"ProjectManagement.Controllers.TokenAuthController GoogleAuthenticate", "Trang Login"},
            {"ProjectManagement.MultiTenancy.TenantAppService CreateAsync", "Trang Admin > Tenants"},
            {"ProjectManagement.MultiTenancy.TenantAppService DeleteAsync", "Trang Admin > Tenants"},
            {"ProjectManagement.MultiTenancy.TenantAppService GetAllAsync", "Trang Admin > Tenants"},
            {"ProjectManagement.MultiTenancy.TenantAppService GetAsync", "Trang Admin > Tenants"},
            {"ProjectManagement.MultiTenancy.TenantAppService UpdateAsync", "Trang Admin > Tenants"},
            {"ProjectManagement.Roles.RoleAppService AddUserIntoRole", "Trang Admin > Roles"},
            {"ProjectManagement.Roles.RoleAppService ChangeRolePermission", "Trang Admin > Roles"},
            {"ProjectManagement.Roles.RoleAppService CreateAsync", "Trang Admin > Roles"},
            {"ProjectManagement.Roles.RoleAppService DeleteAsync", "Trang Admin > Roles"},
            {"ProjectManagement.Roles.RoleAppService GetAllAsync", "Trang Admin > Roles"},
            {"ProjectManagement.Roles.RoleAppService GetAllPermissions", "Trang Admin > Roles"},
            {"ProjectManagement.Roles.RoleAppService GetAllUserInRole", "Trang Admin > Roles"},
            {"ProjectManagement.Roles.RoleAppService GetAllUserLevel", "Trang Admin > Roles"},
            {"ProjectManagement.Roles.RoleAppService GetAllUserNotInRole", "Trang Admin > Roles"},
            {"ProjectManagement.Roles.RoleAppService GetRoleForEdit", "Trang Admin > Roles"},
            {"ProjectManagement.Roles.RoleAppService RemoveUserFromOutRole", "Trang Admin > Roles"},
            {"ProjectManagement.Roles.RoleAppService UpdateAsync", "Trang Admin > Roles"},
            {"ProjectManagement.Users.UserAppService AutoUpdateUserFromHRM", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService ChangeLanguage", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService ChangePassword", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService CreateAsync", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService CreateUserByHRMV2Async", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService DeleteFakeUser", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService GetAllActiveUser", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService GetAllAsync", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService GetAllPaging", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService GetAllUserActive", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService GetAsync", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService GetEmployeeInformation", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService GetHistoryProjectsByUserId", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService GetRoles", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService ResetPassword", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService UpdateAsync", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService UpdateAvatar", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService UpdateStarRateFromTimesheet", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService updateUserActive", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService UpdateUserInfo", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService UpdateUserRole", "Trang Admin > Users"},
            {"ProjectManagement.Users.UserAppService updateUserSkill", "Trang Admin > Users"},
            {"ProjectManagement.Web.Host.Controllers.AntiForgeryController SetCookie", "AntiForgeryController"},
            {"ProjectManagement.Web.Host.Controllers.HomeController Index", "Trang Home" },
        };

        public static string GetNote(string serviceName, string methodName)
        {
            if (!Dict.ContainsKey(serviceName + " " + methodName)) return "";
            return Dict[serviceName + " " + methodName];
        }
    }
}
